language: node_js
node_js:
  - "0.12"
before_script:
  - npm install -g grunt-cli
  - npm install -g bower
  - npm install grunt-contrib-qunit grunt
  - bower install

script: grunt test --verbose --force
